import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <div className="fixed inset-0 -z-10">
             <img
            src="/chatbot-bg.jpg"
            alt="후쿠오카"
            className="w-full h-full object-cover"
            // className="w-full h-full object-cover blur-[2px] brightness-100"
            draggable={false}
          />
        </div>
          {children}
      </body>
    </html>
  );
}
